export const FinanceActions = {
  SET_LOANS_DATA: "SET_LOANS_DATA",
  INITIAL_LOAD: "INITIAL_LOAD",
  GET_USER_DATA: "GET_USER_DATA",
  SET_USER_DATA: "SET_USER_DATA",
  SET_BUDGET_DATA: "SET_BUDGET_DATA",
  SET_COLLATERAL_DATA: "SET_COLLATERAL_DATA",
  UPDATE_LOANS_DATA: "UPDATE_LOANS_DATA",
};
